// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JaxPelzerCMSC2240Final.Models
{
    public partial class CourseLinking
    {
        public int LinkId { get; set; }
        public int StuId { get; set; }
        public int CourseId { get; set; }

        public virtual Course Course { get; set; }
        public virtual Student Stu { get; set; }
    }
}