// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JaxPelzerCMSC2240Final.Models
{
    public partial class Course
    {
        public Course()
        {
            CourseLinkings = new HashSet<CourseLinking>();
        }

        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int CourseCredits { get; set; }

        public virtual ICollection<CourseLinking> CourseLinkings { get; set; }
    }
}