// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JaxPelzerCMSC2240Final.Models
{
    public partial class Driver
    {
        public Driver()
        {
            InfractionDriverLinks = new HashSet<InfractionDriverLink>();
            Vehicles = new HashSet<Vehicle>();
        }

        public int DriverId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Ssn { get; set; }

        public virtual ICollection<InfractionDriverLink> InfractionDriverLinks { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}