// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JaxPelzerCMSC2240Final.Models
{
    public partial class Infraction
    {
        public Infraction()
        {
            InfractionDriverLinks = new HashSet<InfractionDriverLink>();
        }

        public int InfractionId { get; set; }
        public string InfractionDesc { get; set; }
        public decimal InfractionCost { get; set; }

        public virtual ICollection<InfractionDriverLink> InfractionDriverLinks { get; set; }
    }
}