// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JaxPelzerCMSC2240Final.Models
{
    public partial class Student
    {
        public Student()
        {
            CourseLinkings = new HashSet<CourseLinking>();
        }

        public int StuId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }

        public virtual ICollection<CourseLinking> CourseLinkings { get; set; }
    }
}