// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JaxPelzerCMSC2240Final.Models
{
    public partial class Vehicle
    {
        public int VehicleId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string LiscencePlateNumber { get; set; }
        public int DriverId { get; set; }

        public virtual Driver Driver { get; set; }

    }
}